### ISSUE TITLE
Random chrashes

### ISSUE THREAD

**Issue by se7en-x230** [0xacx/chatGPT-shell-cli#15]
I have several "bugs"

First the most important one:
Your request to Open AI API failed: server_error
The server had an error while processing your request. Sorry about that!

This happens about every 10 th time.

Second. Image creation
1.  I changed the line nr 50 from "open" to $BROWSER
2.  even so my terminal can do imcat it does not start because it is not a iTerm.app (i guess). So the it would be nicer if possible to change the if statement

**Comment by 0xacx** [comment]
I noticed several server errors yesterday as well. I assume they are from OpenAI's servers working at capacity and failing to complete all the requests, because at the same time I couldn't log in to the ChatGPT site. Sadly, as long as the requests the script sends are properly formatted, with correct headers etc, which they are, there is nothing we can do about OpenAI's servers. 

About the image generation, the command `open` works in MacOS by opening the image in your default browser. I am guessing it's not working properly in Linux. In that case you can use `xdg-open` as you can see @sourav-majumdar-math did [here](https://github.com/0xacx/chatGPT-shell-cli/commit/0dcf4e02e48d0eb1273e05209303dace1a2c8aa7). You can also open the image with an image viewer, or a specific browser but whatever you choose it has to be included in your $PATH. Others have used different packages/solutions to show images in their terminal:
@sourav-majumdar-math used tiv [code](https://github.com/0xacx/chatGPT-shell-cli/commit/6c28fa07cce8097817f4556d0c8c71cdf79fa0ee) 
@pfr-dev used Kitty terminal 
```sh
   if [[ "$TERM" == "xterm-kitty" ]]; then
     curl -sS $image_url -o temp_image.png
       kitty +kitten icat temp_image.png 
```
Let me know if that helps!

**Comment by se7en-x230** [comment]
Excellent.
Thanks for the fast reply.
Yes I thought it might be an overload server. Last night I did use script for an hour and experienced no crashes 

Browse is working and image in terminal also 

Thanks
