### ISSUE TITLE
No followup questions

### ISSUE THREAD

**Issue by se7en-x230** [0xacx/chatGPT-shell-cli#16]
Am I missing something or why can't I ask follow up questions?

**Comment by mountaineerbr** [comment]
You need resend previous prompts and answers. My chatgpt shell wrapper can do it with the `chatgpt.sh -c`. You may want to check that out at my GitHub repo: https://github.com/mountaineerbr/shellChatGPT

**Comment by se7en-x230** [comment]
I like that I can ask follow questions BUT I like the design of this script more.

1. I like that this script starts and keeps running.
2. I love the image: option to start from inside the script
3. I find the other script has too many infos about token, model each time I ask another question.

I wrote a hacky script to choose if to chat via chatgpt.sh -c and keep asking or create images via chatgpt -i 
It works but the information is cluttered due too much "useless" information.

Oh and the downloaded image has each time the same name and therefor overwrites the old file over and over again.

**Comment by mountaineerbr** [comment]
Hey se7en-x230.. Thanks for your feedback.
I occurred to me it should be simple to implement these features in 0xacx'chatgpt.sh because of point \`one' of your last comment. As the script keeps running, that is just a matter to append the previous prompts/answers to the new input. That should be in Q and A format, but the first prompt may be Instructions, so there is that to consider, too. I hope that gets implemented here!

**Comment by 0xacx** [comment]
@se7en-x230 Thank you very much for the feedback! 🙏 
@mountaineerbr Thank you for the feedback, the suggestions and the PR! ✌️ 

@se7en-x230 You probably know this already, but for someone who doesn't, this might be helpful. This script and all other tools that use the **official OpenAI API**, are not the same as the original ChatGPT, in the OpenAI site. If you want to use the exact same API that ChatGPT uses, then you have to look at unofficial API clients like [this](https://github.com/acheong08/ChatGPT) for example. These clients, or tools that are built upon these clients use the actual ChatGPT API but since they are unofficial, they tend to break and some use their own proxy servers to bypass Cloudflare restrictions, which is something to take into account. In theory, this script could use these unofficial clients but since most are written in python and js, it wouldn't be a simple shell script anymore. 😆 
 
Now in the scripts like this one where the official OpenAI API is used, you can try to get close to the real ChatGPT "experience" by sending the history of the chat as context for the model as @mountaineerbr suggested, but still it won't be the same. In any case inspired by this thread and @mountaineerbr 's work I started adding an option for chat context in the script but run into some weird issues while testing, so these changes are not ready to be merged yet.

**Comment by 0xacx** [comment]
I just merged the relevant PR so unless there are other problems or concerns, I think we can close this issue. Thanks again for the help!

**Comment by se7en-x230** [comment]
Thanks
