### ISSUE TITLE
Add interactive command execution feature?

### ISSUE THREAD

**Issue by wjianbo** [0xacx/chatGPT-shell-cli#38]
Would you consider to add an interactive command execution feature.

This feature should allow users to input a command prompt, and then receive a suggestion for a command to execute based on their input. The application should then ask the user whether they would like to execute the suggested command.

I tried something like this:

```
Enter a prompt:
show current folder contents

chatgpt  Execute 'ls'? (Yes/No, Enter=Yes)
chatgpt.sh  install.sh  LICENSE  README.md  test
```

This feature will make the application more intuitive and user-friendly, and will help users who are not familiar with command-line interfaces to use the application more easily.

**Comment by rxaviers** [comment]
If this is done, please do not enable it by default (but consider enabling only if a certain argument is passed). I am afraid of security implications. I don't want to delete my files by mistake for example. Thanks

**Comment by 0xacx** [comment]
@wjianbo I just merged this functionality in https://github.com/0xacx/chatGPT-shell-cli/pull/40 👍 

@rxaviers I agree, and that's why I included a confirmation and warning before executing a command. In practice during testing I found that it is hard to get chatgpt to return a malicious command that is ready to run. Meaning that for simple commands like `rm -rf`, chatgpt has been moderated and responds with "I can't give commands that may harm systems". For more complex commands, chatgpt usually feels the need to explain what is going on, so just running the output directly doesn't work either as it is the command mixed in text. If it starts to become really dangerous I am open to only enable it with a certain flag, but for now as my initial testing showed me, it's not really a big worry as only simple commands are ready to run.
