### ISSUE TITLE
Good practices: Do not automatically add env vars to .profile

### ISSUE THREAD

**Issue by Zeioth** [0xacx/chatGPT-shell-cli#48]
It is ok to ask the user to define the env vars, but it is a bad idea to touch the .profile file ourselves from the installer.

**Comment by 0xacx** [comment]
I agree, it is a bit invasive but I think that users who care about it, would not use the installer anyway and just install the script manually. But, for users that don't know where their shell profile is and how to edit it, the script is very useful. I added a question before editing the shell profile, so it is crystal clear to anyone what happens when running the install script. 👍
